require("dotenv").config();
const c = {
  OunceFactor: 31.1034,
  inputType: {
    TEXT: "text",
    NUMBER: "number",
    SELECT: "select",
    CHECKBOX: "checkbox",
    RADIO: "radio",
    TEXTAREA: "textarea",
  },
  paymentMode: {
    prepaid: "Prepaid",
    COD: "COD",
  },
  userType: {
    Admin: "Admin",
    Customer: "Customer",
    Vendor: "Vendor",
  },
  addressType: {
    Billing: "Billing",
    Shipping: "Shipping",
  },
  syncStatus: {
    Pending: "Pending",
    Completed: "Completed",
    Failed: "Failed",
  },
  productType: {
    Simple: "Simple",
    Configurable: "Configurable",
    // Virtual: "Virtual",
    // Group: "Group",
  },
  productStatus: {
    Draft: "Draft",
    Published: "Published",
    Unpublished: "Unpublished",
    Scheduled: "Scheduled",
  },
  userStatus: {
    Active: "Active",
    Verified: "Verified",
    Unverified: "Unverified",
    Inactive: "Inactive",
  },
  status: {
    Published: "Published",
    Unpublished: "Unpublished",
  },
  blogStatus: {
    Published: "Published",
    Unpublished: "Unpublished",
  },
  subscriptionStatus: {
    Subscribed: "Subscribed",
    Unsubscribed: "Unsubscribed",
  },
  orderStatus: {
    Pending: "Pending",
    Processing: "Processing",
    Completed: "Completed",
    Cancelled: "Cancelled",
    Returned: "Returned",
    Failed: "Failed",
  },
  quoteStatus: {
    Creating: "Creating",
    Submitted: "Submitted",
    Processing: "Processing",
    Completed: "Completed",
    Cancelled: "Cancelled",
  },
  itemStatus: {
    Submitted: "Submitted",
    Processing: "Processing",
    Completed: "Completed",
    Cancelled: "Cancelled",
  },
  forceUpdate: {
    attribute: false,
    product: false,
    category: false,
    brands: false,
    user: false,
  },
  status: {
    Published: "Published",
    Unpublished: "Unpublished",
  },
  subcribeStatus: {
    Subscribed: "Subscribed",
    UnSubscribed: "UnSubscribed",
  },
  couponType: {
    Percent: "Percent",
    Numeric: "Numeric",
  },

  couponMode: {
    Product: "Product",
    Category: "Category",
    Brand: "Brand",
    Cart: "Cart",
  },
  dealType: {
    BUY_PRODUCT_GET_PRODUCT: "Buy some product(s) & get another free",
    BUY_PRODUCT_GET_PERCENT_DISCOUNT: "Buy some product(s) get percent off",
    BUY_PRODUCT_GET_NUMERIC_DISCOUNT: "Buy some product(s) get flat off",

    BUY_TOTAL_GET_PRODUCT: "Get free product on cart value",
    BUY_TOTAL_GET_PERCENT_DISCOUNT: "Get percent off on cart value",
    BUY_TOTAL_GET_NUMERIC_DISCOUNT: "Get flat off on cart value",
  },
  syncStatus: {
    Queued: "Queued",
    Running: "Running",
    Completed: "Completed",
    Failed: "Failed",
  },
  allowedGoldQuality: ["9KT", "14KT", "18KT", "SL925", "PT950"],
  notAllowedCategory: ["Logo", "N/A", "Raw Material"],

  AI_MODELS: {
    openAi: {
      config: {
        baseURL: 'https://api.openai.com',
        apiKey: process.env.OPENAI_API_KEY, // This is the default and can be omitted
      },
      model: 'gpt-4o-mini'
    },
    openAiImage: {
      config: {
        apiKey: process.env.OPENAI_API_KEY, // This is the default and can be omitted
      },
      model: 'gpt-4o'
    },
    deepseek: {
      config: {
        baseURL: 'https://api.deepseek.com',
        apiKey: 'sk-1004b3b1a4374d0f9986cda97466772b'
      },
      model: 'deepseek-chat'
    }
  },
  conversionTable: {
    PT950: {
      PT950: 1,
      G24W: 2.736 / 3.04,
      G22W: 2.496 / 3.04,
      G18W: 2.144 / 3.04,
      G14W: 1.824 / 3.04,
      G10W: 1.6 / 3.04,
      G09W: 1.6 / 3.04,
      SL925: 1.488 / 3.04,
    },
    G24W: {
      PT950: 3.04 / 2.736,
      G24W: 1,
      G22W: 2.496 / 2.736,
      G18W: 2.144 / 2.736,
      G14W: 1.824 / 2.736,
      G10W: 1.6 / 2.736,
      G09W: 1.6 / 2.736,
      SL925: 1.488 / 2.736,
    },
    G22W: {
      PT950: 3.04 / 2.496,
      G24W: 2.736 / 2.496,
      G22W: 1,
      G18W: 2.144 / 2.496,
      G14W: 1.824 / 2.496,
      G10W: 1.6 / 2.496,
      G09W: 1.6 / 2.496,
      SL925: 1.488 / 2.496,
    },
    G18W: {
      PT950: 3.04 / 2.144,
      G24W: 2.736 / 2.144,
      G22W: 2.496 / 2.144,
      G18W: 1,
      G14W: 1.824 / 2.144,
      G10W: 1.6 / 2.144,
      G09W: 1.6 / 2.144,
      SL925: 1.488 / 2.144,
    },
    G18: {
      PT950: 3.04 / 2.144,
      G24W: 2.736 / 2.144,
      G22W: 2.496 / 2.144,
      G18W: 1,
      G14W: 1.824 / 2.144,
      G10W: 1.6 / 2.144,
      G09W: 1.6 / 2.144,
      SL925: 1.488 / 2.144,
    },
    G14W: {
      PT950: 3.04 / 1.824,
      G24W: 2.736 / 1.824,
      G22W: 2.496 / 1.824,
      G18W: 2.144 / 1.824,
      G14W: 1,
      G10W: 1.6 / 1.824,
      G09W: 1.6 / 1.824,
      SL925: 1.488 / 1.824,
    },
    G14: {
      PT950: 3.04 / 1.824,
      G24W: 2.736 / 1.824,
      G22W: 2.496 / 1.824,
      G18W: 2.144 / 1.824,
      G14W: 1,
      G10W: 1.6 / 1.824,
      G09W: 1.6 / 1.824,
      SL925: 1.488 / 1.824,
    },
    G10W: {
      PT950: 3.04 / 1.6,
      G24W: 2.736 / 1.6,
      G22W: 2.496 / 1.6,
      G18W: 2.144 / 1.6,
      G14W: 1.824 / 1.6,
      G10W: 1,
      G09W: 1,
      SL925: 1.488 / 1.6,
    },
    G09W: {
      PT950: 3.04 / 1.6,
      G24W: 2.736 / 1.6,
      G22W: 2.496 / 1.6,
      G18W: 2.144 / 1.6,
      G14W: 1.824 / 1.6,
      G10W: 1,
      G09W: 1,
      SL925: 1.488 / 1.6,
    },
    G09: {
      PT950: 3.04 / 1.6,
      G24W: 2.736 / 1.6,
      G22W: 2.496 / 1.6,
      G18W: 2.144 / 1.6,
      G14W: 1.824 / 1.6,
      G10W: 1,
      G09W: 1,
      SL925: 1.488 / 1.6,
    },
    SL925: {
      PT950: 3.04 / 1.488,
      G24W: 2.736 / 1.488,
      G22W: 2.496 / 1.488,
      G18W: 2.144 / 1.488,
      G14W: 1.824 / 1.488,
      G10W: 1.6 / 1.488,
      G09W: 1.6 / 1.488,
      SL925: 1,
    }
  },
  segmentEventName: {
    categoryFilterApplied: "Category_filter_applied",
    hashtagFilterApplied: "Hashtag_filter_applied",
    searchStringFilterApplied: "Search_string_filter_applied",
    subcategoryFilterApplied: "Subcategory_filter_applied",
    designViewDetailsClicked: "Design_view_details_clicked",
    centerStoneShapeFilterApplied: "Center_stone_shape_filter_applied",
    sideStonesShapeFilterApplied: "Side_stones_shape_filter_applied",
    aiSearchImageClicked: "Ai_search_image_clicked",
    aiSearchImageResponseReceived: "Ai_search_image_response_received",
    diamondWtFilterApplied: "Diamond_wt_filter_applied",
    centerStoneFilterApplied: "Center_stone_filter_applied",
    stoneRangeFilterApplied: "Stone_range_filter_applied",
    generatedPdfForCatalog: "Generated_pdf_for_catalog",
    exportSelectionBucketClicked: "Export_selection_bucket_clicked",
    commentLogsPanelOpened: "Comment_logs_panel_opened",
    addToQuoteClicked: "Add_to_quote_clicked",
    bulkDeleteSelectedItemsClicked: "Bulk_delete_selected_items_clicked",
    aiSearchTextClicked: "Ai_search_text_clicked",
    showMyDesignsFilterApplied: "Show_my_designs_filter_applied",
    weightRangeFilterApplied: "Weight_range_filter_applied",
    addToFavouritesClicked: "Add_to_favourites_clicked",
    calculatePriceClicked: "Calculate_price_clicked",
    uploadMoreImagesClicked: "Upload_more_images_clicked",
    createdNewCatalog: "Created_new_catalog",
    viewedCatalog: "Viewed_catalog",
    deletedCatalog: "Deleted_catalog",
    sideStonesFilterApplied: "Side_stones_filter_applied",
    addToSelectionClicked: "Add_to_selection_clicked",
    clickedProceedToGetPricing: "Clicked_proceed_to_get_pricing",
    removeFromFavouritesClicked: "Remove_from_favourites_clicked",
    exportedCatalogToExcel: "Exported_catalog_to_excel"
  },
  materialShape: {
    ARC: "Arrow",
    ASCP: "Asscher Pointer",
    ASC: "Asscher",
    BAG: "Baguette",
    BAGP: "Baguette Pointer",
    BLT: "Bullet",
    BRL: "Briolette",
    CAD: "Cadilac",
    CLF: "Calf",
    COL: "Clover",
    CRS: "Cross",
    CUS: "Cushion",
    CUSP: "Cushion Pointer",
    CUSR: "Cushion Round",
    DRP: "Drop",
    EMC: "Emerald",
    EMCP: "Emerald Pointer",
    FLS: "Flander",
    FLW: "Flower",
    HEX: "Hexagon",
    HRT: "Heart",
    KTE: "Kite",
    LZN: "Lozenge",
    MON: "Moon",
    MQRP: "Marquise Pointer",
    MRQ: "Marquise",
    OCT: "Octagon",
    OVL: "Oval",
    PER: "Pear",
    PIE: "Pie",
    PRC: "Princess",
    PRCP: "Princess Pointer",
    RDT: "Radiant",
    RDTP: "Radiant Pointer",
    RND: "Round",
    RNDP: "Round Pointer",
    SHD: "Shield",
    STR: "Star",
    TRG: "Tringle",
    TRI: "Trillion",
    TRP: "Trapezium"
  },
  activityType: {
    LOGIN: "Logged in",
    LOGOUT: "Logged out",
    PRICING_REQUEST: "Pricing Request",
    AI_IMAGE_SEARCH: "Generated AI image search",
    DESIGN_FILTER_REQUEST: "Design Filter Request",
  },
  cacheKeyName:{
    materialPrice:"materialPrice"
  }

};
module.exports = c;
